# Generated by Django 5.1.6 on 2025-02-28 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("guests", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("beds", models.IntegerField()),
                ("baths", models.IntegerField()),
                ("amenities", models.JSONField(default=list)),
                ("price", models.FloatField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
