"""Updated listings model

Revision ID: 03585c5cb5f3
Revises: 1952c4364990
Create Date: 2024-11-10 18:14:26.515285

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03585c5cb5f3"
down_revision: Union[str, None] = "1952c4364990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column(
            "tagline", sa.String(), server_default="default_tagline", nullable=False
        ),
    )
    op.add_column(
        "listings",
        sa.Column(
            "location", sa.String(), server_default="default_location", nullable=False
        ),
    )
    op.add_column(
        "listings",
        sa.Column(
            "image", sa.String(), server_default="default_image_url", nullable=False
        ),
    )
    op.add_column(
        "listings", sa.Column("price", sa.Float(), default=0.0, nullable=False)
    )
    op.drop_column("listings", "description")
    op.drop_column("listings", "bedrooms")
    op.drop_column("listings", "mean_rating")
    op.drop_column("listings", "count_ratings")
    op.drop_column("listings", "nightly_price")
    op.drop_column("listings", "beds")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings", sa.Column("beds", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "listings",
        sa.Column(
            "nightly_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "listings",
        sa.Column("count_ratings", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "listings",
        sa.Column(
            "mean_rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "listings",
        sa.Column("bedrooms", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "listings",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("listings", "price")
    op.drop_column("listings", "image")
    op.drop_column("listings", "location")
    op.drop_column("listings", "tagline")
    # ### end Alembic commands ###
