name: Run Postman Update

on: push

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name:
        run: |
          docker compose up -d --build
